{{$NAMESPACES := DefaultParam .NAMESPACES "5"}}
{{$CONFIGMAPS_PER_NS := DefaultParam .CONFIGMAPS_PER_NS "100"}}
{{$SECRETS_PER_NS := DefaultParam .SECRETS_PER_NS "100"}}
{{$UPDATE_ITERATIONS := DefaultParam .UPDATE_ITERATIONS "10"}}

name: configmap-secret-churn
namespace:
  number: {{$NAMESPACES}}
  prefix: cl2-test
tuningSets:
  - name: Uniform5qps
    qpsLoad:
      qps: 5
steps:
  - name: Start measurements
    measurements:
      - Identifier: APIResponsiveness
        Method: APIResponsivenessPrometheusSimple
        Params:
          action: start
      - Identifier: ResourceUsageSummary
        Method: ResourceUsageSummary
        Params:
          action: start
  - name: Create configmaps
    phases:
      - namespaceRange:
          min: 1
          max: {{$NAMESPACES}}
        replicasPerNamespace: {{$CONFIGMAPS_PER_NS}}
        tuningSet: Uniform5qps
        objectBundle:
          - basename: churn-configmap
            objectTemplatePath: configmap.yaml
            templateFillMap:
              Data: "{{RandData 1024}}"
  - name: Create secrets
    phases:
      - namespaceRange:
          min: 1
          max: {{$NAMESPACES}}
        replicasPerNamespace: {{$SECRETS_PER_NS}}
        tuningSet: Uniform5qps
        objectBundle:
          - basename: churn-secret
            objectTemplatePath: secret.yaml
            templateFillMap:
              SecretData: "{{RandData 1024}}"
  {{range $i := Loop {{$UPDATE_ITERATIONS}}}}
  - name: Update configmaps iteration {{$i}}
    phases:
      - namespaceRange:
          min: 1
          max: {{$NAMESPACES}}
        replicasPerNamespace: {{$CONFIGMAPS_PER_NS}}
        tuningSet: Uniform5qps
        objectBundle:
          - basename: churn-configmap
            objectTemplatePath: configmap.yaml
            templateFillMap:
              Data: "{{RandData 1024}}"
  - name: Update secrets iteration {{$i}}
    phases:
      - namespaceRange:
          min: 1
          max: {{$NAMESPACES}}
        replicasPerNamespace: {{$SECRETS_PER_NS}}
        tuningSet: Uniform5qps
        objectBundle:
          - basename: churn-secret
            objectTemplatePath: secret.yaml
            templateFillMap:
              SecretData: "{{RandData 1024}}"
  {{end}}
  - name: Gather measurements
    measurements:
      - Identifier: APIResponsiveness
        Method: APIResponsivenessPrometheusSimple
        Params:
          action: gather
      - Identifier: ResourceUsageSummary
        Method: ResourceUsageSummary
        Params:
          action: gather
