apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    group: cl2-test
spec:
  type: ClusterIP
  selector:
    name: {{.Name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
